services:
  # Backend Service
  - type: web
    name: signlingo-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: cd src && uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
    buildFilter:
      paths:
        - backend/**/*.py
        - backend/requirements.txt
      ignoredPaths:
        - backend/**/*.pyc
        - backend/**/__pycache__/**

  # Frontend Service
  - type: web
    name: signlingo-frontend
    env: node
    region: oregon
    plan: free
    branch: main
    rootDir: frontend
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 18.17.0
      - key: NEXT_PUBLIC_API_URL
        value: https://signlingo-backend-y554.onrender.com
      - key: NEXT_PUBLIC_WS_URL
        value: wss://signlingo-backend-y554.onrender.com/ws
    buildFilter:
      paths:
        - frontend/**/*.ts
        - frontend/**/*.tsx
        - frontend/**/*.js
        - frontend/**/*.jsx
        - frontend/**/*.css
        - frontend/package.json
        - frontend/package-lock.json
      ignoredPaths:
        - frontend/**/*.test.ts
        - frontend/**/*.test.tsx
        - frontend/**/*.spec.ts
        - frontend/**/*.spec.tsx
